### ISSUE TITLE
Disallow self-referencing commands

### ISSUE THREAD

**Issue by kenellorando** [za419/CadenceBot#36]
CadenceBot can execute commands against itself. The `echo` command is dangerous and should not be allowed to call further commands.

Bot behavior:
![image](https://user-images.githubusercontent.com/17265041/73598739-aee8d600-4501-11ea-8ece-f6e3fb5441e6.png)

User sentiment:
![image](https://user-images.githubusercontent.com/17265041/73598756-e2c3fb80-4501-11ea-95a5-8b0ca175283f.png)

**Comment by za419** [comment]
This has been fixed by banning CadenceBot from itself.
