### ISSUE TITLE
Implement detailed helptext for each command

### ISSUE THREAD

**Issue by za419** [za419/CadenceBot#57]
Extend `Cadence help` to be able to take the name of a command and print helptext for it. Some thinking might need to happen to make the 'name' configurable enough.

This helptext should be a detailed, and full specification of how the command functions - ie search should describe special forms provided by the server.

Discussion is welcome over how, and indeed whether, automatically generated documentation of custom commands can be included in this (@kenellorando )

**Comment by za419** [comment]
Detailed helptext for `help` is now done, as part of #58.

**Comment by za419** [comment]
Commands that need documenting:

- [x] Play
- [ ] Stop
- [x] Help
- [ ] Nowplaying
- [ ] Search
- [ ] Request
- [ ] Library

Non-command topics that need documenting for this issue to be considered resolved:

- [ ] Admin (general)
- [x] Bans (see #59)
- [ ] Debugging (covering maillog and config in more depth? Not sure if this is worth doing.)

Non-command topics that need documenting, but not as part of this issue:

- [ ] Custom Commands (~~This will require special-casing of the helptext generation, and should generate some summary information of each command - Ex "Cadence flip a coin - Randomly prints a result. Cadence echo to <user> <string> - Prints a result dependent on <string> and the mentioned <user>." - No details of how the command actually functions, but documentation of existence, what goes into using it, and randomness.~~ See  #60 )

Any ideas for more?

**Comment by magix430** [comment]
I would like to stake a claim on helptext for Play if it has not yet been claimed.

**Comment by za419** [comment]
Play is all yours, @magix430

**Comment by za419** [comment]
I am canceling this task in favor of more granular tasks for each PR and the project to track overall status.
