### ISSUE TITLE
Allow aliasing of topics in the helpTopic command

### ISSUE THREAD

**Issue by JunhaoSLi** [za419/CadenceBot#76]
After discussion in issue #70 (and further offline discussion), it's decided that we want to be able to provide aliases for commands in the config so that multiple phrases can be used for a command to get the helptext for that command.

e.g. it should be possible for both "Cadence help nowplaying" and "Cadence help now playing" to generate helptext for the nowplaying command.

example of possible config format for this feature
```
"helpTopics": {
    "nowplaying": {
        "internalKey": "nowplaying",
        "subtitle": ...,
        "lines": [...],
    },
    "now playing": {
        "alias": "nowplaying"
    }
}
```

**Comment by za419** [comment]
I'm considering this closed by #86 (Issue fixes in dev-master are good enough...)
